services:
   angular:
     container_name: angular_multi-stage
     image: multi-stage:1.0.0
     build:
       dockerfile: Dockerfile
       context: .
     environment:
       - TZ=Asia/Bangkok
     ports:
       - 8801:80
